Add DNS TXT and CAA record for staging-cd crossfeed
cisagov/cool-dns-cyber.dhs.gov pull request #104
Opened 2024-09-04 18:16 UTC by cduhn17

Add DNS TXT and CAA record for staging-cd

#  #

## 🗣 Description ##

We need to update the TXT and CAA record for the DNS to create a certificate for Let'sEncrypt. terraform-docs has been run.

Add/Update the crossfeed_staging_cd_TXT

## 💭 Motivation and context ##

There are no existing ACME certs

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

2024-09-04 18:31 UTC, jsf9k requested changes
In the future, please give your commits more meaningful commit messages than "Update blah.tf".  The commit message should explain what is being changed and why.

2024-09-04 18:31 UTC, jsf9k commented on README.md
> +## Providers
Please fix the lack of closing octothorps throughout this file.

2024-09-04 18:35 UTC, cduhn17 commented on README.md
> +## Providers
Done

2024-09-04 18:53 UTC, jsf9k approved these changes

2024-09-04 19:16 UTC, cduhn17 commented
@jsf9k , 
I had a failure and updated the LE value

2024-09-04 19:28 UTC, dav3r commented
@cduhn17 I applied the latest Terraform here, which updated the value in the TXT record.  Please let us know if you're all set now.

2024-09-04 19:41 UTC, cduhn17 commented
> @cduhn17 I applied the latest Terraform here, which updated the value in the TXT record. Please let us know if you're all set now.

Can you apply again. Didnt think I was going to have to have an additional CAA for staging-cd. Thanks

2024-09-04 19:47 UTC, dav3r commented
> > @cduhn17 I applied the latest Terraform here, which updated the value in the TXT record. Please let us know if you're all set now.
> 
> Can you apply again. Didnt think I was going to have to have an additional CAA for staging-cd. Thanks

OK, I just reapplied after the changes in https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/104/commits/b6e571c413b1612820f1619076b5569ac828c623.

2024-09-04 21:46 UTC, dav3r approved these changes

2024-09-05 11:44 UTC, cduhn17 commented
The DNS record update was successful

2024-09-05 13:49 UTC, dav3r commented
@cduhn17 Can you please revert https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/104/commits/9e9c25a13038e1116eb97e3d085c46db0d30f23d so that I can merge this PR?  After that, you can recreate a new PR  with the same contents as https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/104/commits/9e9c25a13038e1116eb97e3d085c46db0d30f23d (or reopen #105) and we can get that one reviewed, applied, and merged.

We want to ensure that our Terraform code is aligned with what is actually deployed in AWS.  Thanks!

2024-09-05 14:00 UTC, cduhn17 commented
@dav3r revert is complete

2024-09-05 14:02 UTC, merged