Add Crossfeed integration and api.integration records (A, AAAA, TXT, CAA)
cisagov/cool-dns-cyber.dhs.gov pull request #113
Opened 2024-11-14 18:44 UTC by cduhn17

Update domain name for integration

## 🗣 Description ##

We need to add the api.integration domain name and issue letsencrypt ssl certificates. There is a need for both a TXT record and CAA record and adding AAAA and A records for integration.

## 💭 Motivation and context ##

There are no existing ACME certs

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

2024-11-14 18:45 UTC, cduhn17 commented
@dav3r , I have some code commented out that will be a follow-on PR, I have this commented out because I have to have the SSL cert in place before I can get the values from AWS for the AAAA and A records for api.integration.crossfeed.cyber.dhs.gov

2024-11-14 18:54 UTC, dav3r commented
> @dav3r , I have some code commented out that will be a follow-on PR, I have this commented out because I have to have the SSL cert in place before I can get the values from AWS for the AAAA and A records for api.integration.crossfeed.cyber.dhs.gov

Please remove the commented-out code since it's not relevant to this PR - it should be added in your next PR.

2024-11-14 18:55 UTC, jsf9k approved these changes

2024-11-14 18:56 UTC, dav3r commented on route53_crossfeed_app.tf
> +
Add a section header for integration API entries:
```suggestion

# ------------------------------------------------------------------------------
# Integration API entries
# ------------------------------------------------------------------------------

```

2024-11-14 19:07 UTC, jsf9k commented
@cduhn17 - When you make a change please ensure that the commit message speaks to the change that was made.  "Update route53_crossfeed_app.tf" is very generic and tells a future developer nothing about the content of the commit.

2024-11-14 19:12 UTC, cduhn17 commented
@dav3r am I GTG after a tf apply? Thanks

2024-11-14 19:16 UTC, dav3r commented on route53_crossfeed_app.tf
> +
Remove unused code:
```suggestion
```

2024-11-14 19:20 UTC, cduhn17 commented
@dav3r My intent with the commented out code was that the code will be added right after this PR is applied. But i removed it for now. Thanks

2024-11-14 19:21 UTC, dav3r commented
> @dav3r My intent with the commented out code was that the code will be added right after this PR is applied. But i removed it for now. Thanks

Sorry, that wasn't clear before - I thought you meant that code was going to be added in a subsequent PR.

2024-11-14 19:22 UTC, cduhn17 commented
Let me know when i can try the verification. Thanks

2024-11-14 19:32 UTC, dav3r commented
> Let me know when i can try the verification. Thanks

The changes have been applied - give it a shot.

2024-11-14 20:41 UTC, cduhn17 commented
Thanks all i have the certificates in hand

2024-11-14 21:01 UTC, dav3r commented on route53_crossfeed_app.tf
> +# The following A and AAAA will follow once we have the SSL certificate for the API integration environment
This comment is no longer needed.
```suggestion
```

2024-11-14 21:08 UTC, dav3r requested changes

2024-11-14 21:08 UTC, dav3r commented on route53_crossfeed_app.tf
> +}
These two resource blocks should be moved down into the "Integration API entries" section and placed to preserve alphabetical ordering by resource name.

2024-11-14 21:08 UTC, dav3r commented on route53_crossfeed_app.tf
> +}
This resource block should be moved up to preserve alphabetical ordering by resource name in the "Integration entries" section.

2024-11-14 21:08 UTC, dav3r commented on route53_crossfeed_app.tf
> +}
This resource block should be moved up to preserve alphabetical ordering by resource name in the "Integration entries" section.

2024-11-14 21:18 UTC, cduhn17 commented on route53_crossfeed_app.tf
> +}
Moved order to alphabetize record type per commit 
[4071b5b](https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/113/commits/4071b5be643565b9ce3a896931f5a7db24de79de)

2024-11-14 21:18 UTC, cduhn17 commented on route53_crossfeed_app.tf
> +}
Moved order to alphabetize record type per commit 
[4071b5b](https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/113/commits/4071b5be643565b9ce3a896931f5a7db24de79de)

2024-11-14 21:24 UTC, dav3r commented
@cduhn17 I applied the current Terraform and created the integration API A and AAA records.  Please let me know if there is anything else planned in this PR.

2024-11-15 12:33 UTC, cduhn17 commented
@dav3r , Thanks for all of your help. There is nothing further for this PR

2024-11-15 15:32 UTC, dav3r approved these changes
LGTM

2024-11-15 15:34 UTC, dav3r commented on route53_crossfeed_app.tf
> +}
This was handled in https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/113/commits/4071b5be643565b9ce3a896931f5a7db24de79de.

2024-11-15 15:34 UTC, merged